# Generated by Django 3.1.2 on 2022-09-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tatuador', models.CharField(default='', max_length=100)),
                ('Fecha', models.DateField()),
                ('Hora', models.TimeField()),
                ('Imagen', models.ImageField(upload_to='')),
                ('Descripcion', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='')),
                ('descripcion', models.TextField(max_length=200)),
                ('tatuador', models.CharField(max_length=50)),
                ('fecha_publicacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RegistroTatuadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.TextField()),
                ('fecha_nacimiento', models.DateField()),
                ('ciudad', models.TextField()),
                ('departamento', models.TextField()),
                ('email', models.TextField()),
                ('experiencia', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroUsuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.TextField()),
                ('fecha_nacimiento', models.DateField()),
                ('ciudad', models.TextField()),
                ('departamento', models.TextField()),
                ('direccion', models.TextField()),
                ('email', models.TextField()),
            ],
        ),
    ]
